//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace R6S_mouse_sensitivity.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DPI_X {
            get {
                return ((double)(this["DPI_X"]));
            }
            set {
                this["DPI_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DPI_Y {
            get {
                return ((double)(this["DPI_Y"]));
            }
            set {
                this["DPI_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DPI_MAX {
            get {
                return ((double)(this["DPI_MAX"]));
            }
            set {
                this["DPI_MAX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Without_change_ADS_G_X {
            get {
                return ((double)(this["Without_change_ADS_G_X"]));
            }
            set {
                this["Without_change_ADS_G_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Without_change_ADS_G_Y {
            get {
                return ((double)(this["Without_change_ADS_G_Y"]));
            }
            set {
                this["Without_change_ADS_G_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Without_change_ADS_ADS {
            get {
                return ((double)(this["Without_change_ADS_ADS"]));
            }
            set {
                this["Without_change_ADS_ADS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Without_change_ADS_MSMU {
            get {
                return ((double)(this["Without_change_ADS_MSMU"]));
            }
            set {
                this["Without_change_ADS_MSMU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Without_change_ADS_XFA {
            get {
                return ((double)(this["Without_change_ADS_XFA"]));
            }
            set {
                this["Without_change_ADS_XFA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Without_change_ADS_DPI {
            get {
                return ((double)(this["Without_change_ADS_DPI"]));
            }
            set {
                this["Without_change_ADS_DPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XFA_5 {
            get {
                return ((double)(this["XFA_5"]));
            }
            set {
                this["XFA_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double G_X_5 {
            get {
                return ((double)(this["G_X_5"]));
            }
            set {
                this["G_X_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double G_Y_5 {
            get {
                return ((double)(this["G_Y_5"]));
            }
            set {
                this["G_Y_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ADS_5 {
            get {
                return ((double)(this["ADS_5"]));
            }
            set {
                this["ADS_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MSMU_5 {
            get {
                return ((double)(this["MSMU_5"]));
            }
            set {
                this["MSMU_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string gamesettings_folder {
            get {
                return ((string)(this["gamesettings_folder"]));
            }
            set {
                this["gamesettings_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gamesettings_set_check {
            get {
                return ((bool)(this["gamesettings_set_check"]));
            }
            set {
                this["gamesettings_set_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string gamesettings_bkup {
            get {
                return ((string)(this["gamesettings_bkup"]));
            }
            set {
                this["gamesettings_bkup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool change_mouse_sensitivity_os_Accuracy {
            get {
                return ((bool)(this["change_mouse_sensitivity_os_Accuracy"]));
            }
            set {
                this["change_mouse_sensitivity_os_Accuracy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool change_mouse_sensitivity_os_UnAccuracy {
            get {
                return ((bool)(this["change_mouse_sensitivity_os_UnAccuracy"]));
            }
            set {
                this["change_mouse_sensitivity_os_UnAccuracy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool change_mouse_sensitivity_MSMU_Change {
            get {
                return ((bool)(this["change_mouse_sensitivity_MSMU_Change"]));
            }
            set {
                this["change_mouse_sensitivity_MSMU_Change"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool change_mouse_sensitivity_read_Y {
            get {
                return ((bool)(this["change_mouse_sensitivity_read_Y"]));
            }
            set {
                this["change_mouse_sensitivity_read_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool option_Detailed_Value {
            get {
                return ((bool)(this["option_Detailed_Value"]));
            }
            set {
                this["option_Detailed_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool option_Save_Data {
            get {
                return ((bool)(this["option_Save_Data"]));
            }
            set {
                this["option_Save_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool option_Back_Up {
            get {
                return ((bool)(this["option_Back_Up"]));
            }
            set {
                this["option_Back_Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool initialize {
            get {
                return ((bool)(this["initialize"]));
            }
            set {
                this["initialize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Change_dpi_per_ingame_DPI {
            get {
                return ((double)(this["Change_dpi_per_ingame_DPI"]));
            }
            set {
                this["Change_dpi_per_ingame_DPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Change_dpi_per_ingame_G_X {
            get {
                return ((double)(this["Change_dpi_per_ingame_G_X"]));
            }
            set {
                this["Change_dpi_per_ingame_G_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Change_dpi_per_ingame_G_Y {
            get {
                return ((double)(this["Change_dpi_per_ingame_G_Y"]));
            }
            set {
                this["Change_dpi_per_ingame_G_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Change_dpi_per_ingame_MSMU {
            get {
                return ((double)(this["Change_dpi_per_ingame_MSMU"]));
            }
            set {
                this["Change_dpi_per_ingame_MSMU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string gamesettings_file {
            get {
                return ((string)(this["gamesettings_file"]));
            }
            set {
                this["gamesettings_file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool option_Default_file {
            get {
                return ((bool)(this["option_Default_file"]));
            }
            set {
                this["option_Default_file"] = value;
            }
        }
    }
}
